#!/bin/bash
#
# scripts/host2pkg:
#	This script creates the packages needed to support
# the example jails in examples/ using files installed on
# the host system.
#
# Eventually we'll make a better tool for this maybe?

#	equery list \* --format="\$name" |
# Scan through 
if [ "$(which equery 2>/dev/null)x" != "x" ]; then
   equery -C files $1 |  tar --no-recursion -T- -c -v -f pkg/$1.tar; \
fi
if [ "$(which pacman 2>/dev/null)x" != "x" ]; then
   pacman -Ql $1 | cut -f 2- -d ' ' | tar --no-recursion -T- -c -v -f pkg/$1.tar;
fi
