#!/bin/bash
#
# scripts/host2pkg:
#	This script creates the packages needed to support
# the example jails in examples/ using files installed on
# the host system.
#
# Eventually we'll make a better tool for this maybe?

#	equery list \* --format="\$$name" |
# Scan through 
for line in "; do \
   if [ "$(which equery)x" != "x" ]; then
      equery -C files $$line |  tar --no-recursion -T- -c -v -f /pkg/$$line.tar; \
   fi
   if [ "$(which pacman)x" != "x" ]; then
      pacman -Ql $$line | cut -f 2- -d ' ' | tar --no-recursion -T- -c -v -f /pkg/$$line.tar;
   fi
done
